# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-seek-deployment
  description: Get deployment ID by environment, reference or status
  homepage: https://cloudposse.com/accelerate
  topics: ""
