name: 'Get Deployment ID'
description: 'Get an deployment ID for a specific REF and environment'
inputs:
  github-token: 
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
  ref:
    description: 'Branch or commit SHA'
    required: true
  environment:
    description: 'Environment name'
    required: true
  status:
    description: 'status to get ID for'
    required: false
outputs:
  id: 
    description: 'Deployment ID'
runs:
  using: 'node12'
  main: 'index.js'
