name: 'Seek Deployment'
description: 'Seek Deployment for a specific `ref`, `environment` and `status`'
author: james-leha@github.com, hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  github-token: 
    description: The GitHub token
    default: ${{ github.token }}
    required: true
  ref:
    description: 'Branch or commit SHA'
    required: true
  environment:
    description: 'Environment name'
    required: true
  status:
    description: 'Deployment status'
    required: false
outputs:
  id: 
    description: 'Top Deployment ID'
  ids: 
    description: 'All Matching Deployment IDs'
runs:
  using: 'node20'
  main: 'index.js'
